name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: https://github.com/Sergiy-Galenko/nestJS_zero.git
          username: ${{ secrets.SSergiyHalenko }}
          password: ${{ secrets.g0Ghh-77y9rrrss1l4 }}
          tags: "develop"